"""Application configuration.

All tuneable parameters live here, including pre-computed IIR filter coefficients.
Filter coefficients were generated by scripts/compute_filter_coeffs.py at
DEVICE_SAMPLE_RATE = 2000 Hz.  Re-run that script and paste its output into the
FILTER COEFFICIENTS section below whenever you change the sample rate or cutoffs.
"""

# ---------------------------------------------------------------------------
# Build flags
# ---------------------------------------------------------------------------
# Set EMULATOR_BUILD = True before running `buildozer android debug` to produce
# an APK that skips the 192.168.1.x WiFi check and works with emulator.py.
# Revert to False for production APKs that connect to the real hardware.
EMULATOR_BUILD = True

# ---------------------------------------------------------------------------
# Device
# ---------------------------------------------------------------------------
DEVICE_SAMPLE_RATE = 2000   # Hz — must match DEVICE_FSAMP / DEVICE_MODE below
DEVICE_CHANNELS    = 72
DEVICE_HOST        = "0.0.0.0"
DEVICE_PORT        = 45454
DEVICE_CONNECT_TIMEOUT = 15  # seconds

# Sessantaquattro+ command parameters (see device.py::get_sampling_frequency)
# FSAMP=2, MODE=0 → 2000 Hz / 72 channels
DEVICE_FSAMP = 2
DEVICE_NCH   = 3
DEVICE_MODE  = 0
DEVICE_HPF   = 1

# ---------------------------------------------------------------------------
# Live pipeline filter parameters
# ---------------------------------------------------------------------------
BANDPASS_LOW_HZ  = 20.0    # bandpass lower cutoff (Hz)
BANDPASS_HIGH_HZ = 450.0   # bandpass upper cutoff (Hz)
BANDPASS_ORDER   = 4

NOTCH_FREQ_HZ = 60.0       # power-line notch frequency (Hz)
NOTCH_QUALITY = 30         # notch Q factor
NOTCH_ORDER   = 2

# Minimum sample counts for each filter order (= 3 * max(len(b), len(a)))
FILTER_MIN_SAMPLES_ORDER4 = 27   # 3 * 9
FILTER_MIN_SAMPLES_ORDER1 = 9    # 3 * 3

# ---------------------------------------------------------------------------
# Pre-computed filter coefficients at DEVICE_SAMPLE_RATE = 2000 Hz
# ---------------------------------------------------------------------------

# butter(4, [20/1000, 450/1000], btype='band')
BANDPASS_4_B = [
     0.05851270857137603,  0.0, -0.23405083428550413, 0.0,
     0.3510762514282562,   0.0, -0.23405083428550413, 0.0,
     0.05851270857137603,
]
BANDPASS_4_A = [
     1.0,               -4.309368933349023,   7.9319108380991485,
    -8.550038317529452,  6.301057981557486,   -3.2891058290671884,
     1.0961784703741042, -0.2042146501465009,  0.02359741417722524,
]

# butter(1, [20/1000, 450/1000], btype='band')  — short-data fallback
BANDPASS_1_B = [ 0.4447994860920906, 0.0, -0.4447994860920906]
BANDPASS_1_A = [ 1.0, -1.0523515233982244, 0.11040102781581901]

# butter(4, 10/1000, btype='low')  — TKEO envelope smoothing
LOWPASS_10_4_B = [
    5.845142433144487e-08, 2.3380569732577947e-07, 3.507085459886692e-07,
    2.3380569732577947e-07, 5.845142433144487e-08,
]
LOWPASS_10_4_A = [
    1.0, -3.9179078653919865, 5.7570763791180655,
    -3.7603495076945257, 0.921181929191236,
]

# butter(2, [57/1000, 63/1000], btype='bandstop')  — 60 Hz notch
# notch cutoffs: freq/nyq ± freq/nyq/quality = 60/1000 ± 60/1000/30
NOTCH_60_B = [
     0.9911535951016631, -3.894467033374115,  5.807868018765449,
    -3.8944670333741147,  0.9911535951016629,
]
NOTCH_60_A = [
     1.0,               -3.9117699222074034,  5.807789758354652,
    -3.877164144540828,  0.9823854506141249,
]

# ---------------------------------------------------------------------------
# Real-time plot
# ---------------------------------------------------------------------------
PLOT_DISPLAY_SAMPLES = 4000   # rolling buffer length (~2 s at 2000 Hz)
PLOT_DOWNSAMPLE      = 4      # render every Nth sample (1000 points)
PLOT_CHANNEL_INDEX   = 0      # which channel to display

PLOT_BG_RGBA   = (0.118, 0.118, 0.118, 1.0)  # #1e1e1e
PLOT_LINE_RGBA = (0.0,   0.800, 0.533, 1.0)  # #00cc88

# ---------------------------------------------------------------------------
# Calibration
# ---------------------------------------------------------------------------
CALIBRATION_REST_DURATION   = 3.0   # seconds of quiet baseline
CALIBRATION_MVC_DURATION    = 3.0   # seconds of MVC
CALIBRATION_THRESHOLD_FRAC  = 0.3   # threshold = baseline + frac*(mvc - baseline)

# ---------------------------------------------------------------------------
# Feature analysis defaults
# (Note: bandpass/lowpass defaults must match the pre-computed coefficients above)
# ---------------------------------------------------------------------------
FEATURE_BANDPASS_LOW         = 20.0
FEATURE_BANDPASS_HIGH        = 450.0
FEATURE_SMOOTH_CUTOFF        = 10.0
FEATURE_BASELINE_DURATION    = 0.5    # seconds
FEATURE_K_THRESHOLD          = 8.0
FEATURE_AMPLITUDE_DIVISOR    = 4.0
FEATURE_MIN_PEAK_DISTANCE_SEC = 0.5
FEATURE_BACKTRACK_K          = 3.0
FEATURE_MIN_BURST_DURATION   = 0.05  # seconds
FEATURE_FATIGUE_RMS_THRESHOLD = 0.317
FEATURE_FATIGUE_MF_THRESHOLD  = -0.89
FEATURE_WINDOW_DURATION      = 0.5
FEATURE_STEP_DURATION        = 0.1
FEATURE_BILATERAL_WINDOW_SEC = 0.25
FEATURE_BILATERAL_STEP_SEC   = 0.05

# ---------------------------------------------------------------------------
# Multi-track plot colours (cycled when N tracks > len(list))
# ---------------------------------------------------------------------------
MULTI_TRACK_COLORS = [
    (0.0,  0.80, 0.53, 1),   # teal
    (0.95, 0.55, 0.10, 1),   # orange
    (0.40, 0.60, 1.00, 1),   # blue
    (0.90, 0.30, 0.40, 1),   # pink-red
    (0.55, 0.90, 0.20, 1),   # yellow-green
    (0.80, 0.40, 0.90, 1),   # purple
    (0.20, 0.85, 0.85, 1),   # cyan
    (1.00, 0.80, 0.10, 1),   # yellow
]

# ---------------------------------------------------------------------------
# Heatmap colours (cold = inactive, hot = fully active)
# ---------------------------------------------------------------------------
HEATMAP_COLD_RGB = (0.12, 0.12, 0.12)
HEATMAP_HOT_RGB  = (0.0,  0.90, 0.40)

# ---------------------------------------------------------------------------
# General UI
# ---------------------------------------------------------------------------
UPDATE_RATE_MS = 16   # ~60 fps
